config/routes.rb
Rails.application.routes.draw do

  resources :events

  root 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :media

  FIRST_YEAR = 0
  LAST_YEAR = Time.now.year
  TOTAL_YEARS = - FIRST_YEAR + LAST_YEAR
  PERIODS = [
    ["Antiquite", 0 , 476 ],
    ["Moyen Âge", 476 , 1492],
    ["T.M",1492 , 1789 ],
    ["E.C", 1789, LAST_YEAR]
  ]

  def inrange
    ((start_year - Event::FIRST_YEAR) * 100 / (Event::LAST_YEAR - Event::FIRST_YEAR) * 100 ) / 100
  end

  def self.get_period_percent(range)
    FIRST_YEAR < 0 ? first_year = - FIRST_YEAR : first_year = FIRST_YEAR
    total_range = first_year + LAST_YEAR
    ( range * 100 / total_range * 100 ) / 100
  end
end

app/models/medium.rb
class Medium < ActiveRecord::Base
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
    @highlight = params[:highlight].to_i
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
    @ajax = params[:ajax] == "yes"
    render :layout => !@ajax
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
      if @event.save
        redirect_to @event
      else
        render :edit
      end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :start_year, :icon_type, :latitude, :longitude, :url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<img src="https://s3.eu-central-1.amazonaws.com/walloniatimemachine/logo+WTM/logo.png" style="top:10px; right:10px; position:fixed; z-index:2; width:auto; height:20%;"/>
<div id="container" >
  <div id="map" class="map"></div>
  <div id="slider-container">
      <div class="era list-inline"></div>
    <input id="slider" type="range" min=<%= Event::FIRST_YEAR %> max=<%= Event::LAST_YEAR %> step="10" />
    <div id ="selected-year"></div>
  </div>
</div>

<div id="add_place">

  </div>
</div>


</div>


<% content_for(:after_js) do %>
  <%= javascript_tag do %>

var year = d3.scale.linear()
    .domain([<%= Event::FIRST_YEAR %>, <%= Event::LAST_YEAR %>])
    .range([0, 100]);


var periodPercent = d3.scale.linear()
    .domain([0 , <%= - Event::FIRST_YEAR + Event::LAST_YEAR %>])
    .range([0, 100]);

var arrayOfLatLngs = [];

  <% @events.each do |event| %>
  arrayOfLatLngs.push([<%= event.latitude %>, <%= event.longitude %>]);
  d3.select('#slider-container').insert("i", ":first-child").attr("id","arrow<%= event.id %>").attr("class", "arrow fa fa-caret-down").style('left', year(<%= event.start_year %>)+ '%' );

    <% end %>

    d3.select('.era').append('li').attr('class', 'period <%= Event::PERIODS[0][0][0] %>').attr('class', 'A').style('width', periodPercent(476)+'%').html('<%= Event::PERIODS[0][0] %>');
    d3.select('.era').append('li').attr('class', 'period <%= Event::PERIODS[1][0][0] %>').attr('class', 'M').style('width', periodPercent(1016)+'%').html('<%= Event::PERIODS[1][0] %>');;
    d3.select('.era').append('li').attr('class', 'period <%= Event::PERIODS[2][0][0] %>').attr('class', 'T').style('width', periodPercent(297)+'%').html('<%= Event::PERIODS[2][0] %>');;
    d3.select('.era').append('li').attr('class', 'period <%= Event::PERIODS[3][0][0] %>').attr('class', 'E').style('width', periodPercent(226)+'%').html('<%= Event::PERIODS[3][0] %>');;

var bounds = new L.LatLngBounds(arrayOfLatLngs);



  var tileServer = 'http://{s}.tile.openstreetmap.se/hydda/full/{z}/{x}/{y}.png'

  var tileAttribution = 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>';

  var map = L.map("map",{bounceAtZoomLimits:false, worldCopyJump:true, zoom: 5,maxZoom:20, zoomAnimationThreshold:7, touchZoom:true}).fitBounds(bounds);

  L.tileLayer(tileServer, {attribution: tileAttribution, noWrap:true}).addTo(map);

  var markers = {};
  // var markers = L.markerClusterGroup({showCoverageOnHover:false});

  var markerMap = {};
  var popUpMap = {};
  var myIcon = L.divIcon({
    iconSize: new L.Point(45, 45),
});

  <% @events.each do |event| %>

    var marker = L.marker([<%= event.latitude %>, <%= event.longitude %>], {icon:myIcon});

      marker.id = <%= event.id %>;
      marker.start_year = <%= event.start_year %>;
      marker.period = getperiod(marker.start_year);
      markerMap[<%= event.id %>] = marker;
      popUpMap[<%= event.id %>] = markerMap[<%= event.id %>].bindPopup('<%= event.title %> <p><%= link_to("See more", event_path(event.id), { onclick: "$.fancybox( {href : '" + event_path(event.id) + "?ajax=yes', type: 'ajax'} );return false;" })  %></p>');
      <% if event.icon_type %>
      marker.icon_type = '<%= event.icon_type %>'
      <% end %>
      marker.options.icon.options.className = "icon-round";
      marker.options.icon.options.html = '<div class="icon-circle ' + marker.period[0] + '">' + getIcon('<%= event.icon_type %>') + '</div><div class="tip fa fa-caret-down"></div>';
      // markers.addLayer(marker);
    	<% if @highlight == event.id %>
    	   marker.openPopup();
    	<% end %>
    map.addLayer(marker);
  <% end %>

   document.getElementById('slider').addEventListener('change', function() {

        var selected = this.value;
        d3.select('#selected-year').html(selected);
        console.log("selected ", selected);
      _.each(markerMap, function(marker){

      // range in which the marker pops-up
      var range = 30;

	map.removeLayer(marker);

	if (getperiod(selected) == marker.period){
    marker.options.icon.options.html = '<div class="icon-circle ' + marker.period[0] + '">' + getIcon(marker.icon_type) + '</div><div class="tip fa fa-caret-down"></div>';
    // markers.addLayer(marker);
    // console.log(marker)
    // console.log('markers' + markers);
    // markers.addTo(map);
    marker.addTo(map);
          d3.selectAll('.' + marker.period[0]).transition().style('opacity', '1');
        }else{
          d3.selectAll('.' + marker.period[0]).transition().style('opacity', '0.5');
        }

      if (selected - range < marker.start_year && parseInt(selected) + range > marker.start_year){
          console.log(marker);
        marker.openPopup();
        d3.select('#arrow' + marker.id).style('font-size','1.6em').style('color', 'white');
      }else{
        marker.closePopup();
        d3.select('#arrow' + marker.id).style('font-size','1em').style('color', 'lightgrey');
      }

      });

   <% if @highlight %>
      if( markerMap[<%= @highlight %>] !== undefined ) {
        document.getElementById('slider').value = markers[<%= @highlight %>].start_year;
      }
   <% end %>

});

function getIcon(icon_type){
  switch (icon_type) {
    case  "tree":
        return "<i class='fa fa-tree'></i>";
        break;
    case "monument":
        return "<i class='fa fa-university'></i>";
        break;
    case "plane crash":
        return "<i class='fa fa-fighter-jet'></i>";
        break;
    case "beer places":
        return "<i class='fa fa-beer'></i>";
        break;
    case "artifact":
        return "<i class='fa fa-trophy'></i>";
        break;
   case "events":
        return "<i class='fa fa-users'></i>";
        break;
  case "battle":
        return "<i class='fa fa-bomb'></i>";
        break;
   case "":
        return "<i class='fa fa-circle'></i>";
        break;
    default:
        return "<i class='fa fa-circle'></i>";
        break;
  }
}

function getperiod(start_year){
  switch (true) {
    case start_year < <%=  Event::PERIODS[0][2]%>:
        return "<%= Event::PERIODS[0][0]%>";
        break;
    case start_year > <%= Event::PERIODS[1][1]%> && start_year < <%= Event::PERIODS[1][2]%>:
        return "<%= Event::PERIODS[1][0]%>";
        break;
    case start_year > <%= Event::PERIODS[2][1]%> && start_year < <%= Event::PERIODS[2][2]%>:
        return "<%= Event::PERIODS[2][0]%>";
        break;
    case start_year > <%= Event::PERIODS[3][1]%> && start_year < <%= Event::PERIODS[3][2]%>:
        return "<%= Event::PERIODS[3][0]%>";
        break;
   default:
        return "none";
  }

};


  <% end %>
<% end %>

app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>

app/views/events/show.html.erb
<% if @event.media.any? %>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
	<% @event.media.each_with_index do |m, index| %>
        <li data-target="#myCarousel" data-slide-to="<%= index %>" class="<% if index == 0 %>active<% end %>"></li>
	<% end %>
      </ol>

      <div class="carousel-inner" role="listbox">
	<% @event.media.each_with_index do |m, index| %>
	<div class="item <% if index == 0 %>active<% end %>">
          <img class="first-slide" src="<%= m.url %>">
          <div class="container">
            <div class="carousel-caption">
              <p><%= m.description %></p>
            </div>
          </div>
        </div>
	<% end %>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->
<% end %>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-12">
	  <div class="">
		<% if @ajax %>
			<button class="btn btn-primary" onclick="$.fancybox.close()">Back to map</button>
		<% else %>
			<a class="btn btn-primary" href="/?highlight=<%= @event.id %>" role="button">View on map</a>
		<% end %>
		<% if @event.url %>
		<a class="btn btn-info" href="<%= @event.url %>" target="_blank" role="button">More info</a>
		<% end %>
	  </div>
	  <h2 class="featurette-heading"><%= @event.title %><span class="text-muted"> <%= @event.start_year %></span></h2>
          <p class="lead"><%= @event.description %></p>
        </div>
      </div>

</div>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WalloniaTimeMachine</title>
  <meta name="viewport" content="width=device-width" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon"  type="image/x-icon"  href="../../assets/images/favicon.ico">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Montserrat">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css">
</head>
<body>

  <%= yield %>

  <script src="http://d3js.org/d3.v3.min.js"></script>
  <script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>
  <script src="http://leaflet.github.io/Leaflet.markercluster/dist/leaflet.markercluster.js"></script>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.pack.js" %>
  <%= yield(:after_js) %>

</body>
</html>